@startuml
title Certificate Validation
skinparam style strictuml 
participant Customer #FFFFFF
participant Custom_app #FFFFFF
participant S1Seven #FFFFFF
participant Schemas_server #FFFFFF
Custom_app -> S1Seven: Check supported schemas
S1Seven -> Schemas_server: Check the list of available schemas
Schemas_server -> S1Seven: Return the list of available schemas
S1Seven -> Custom_app: Returned filtered list of supported schemas
Customer -> Custom_app: Create the JSON certificate
Custom_app -> S1Seven: Send the certificate for validation
S1Seven -> Customer: Return certificate or list of errors
@enduml
