name: Build and Deploy

on:
  push:
    branches:
      - main
  release:
    types:
      - published

env:
  S1SevenDocVersion_PATH: /
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Update S1SevenDocVersion_PATH
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo S1SevenDocVersion_PATH=/version/$(echo $GITHUB_REF | cut -d / -f 3 | cut -d v -f 2- | cut -d . -f 1,2)/ >> $GITHUB_ENV

      - name: Install and Build
        run: |
          npm ci
          npm run docs:build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/.vuepress/dist
          target-folder: ${{ env.S1SevenDocVersion_PATH }}
          clean: true
          clean-exclude: '["version"]'
