name: Build and Deploy

on:
  push:
    branches:
      - main
  release:
    types:
      - published

env:
  S1SevenDocVersion_PATH: /

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      # - name: Build and Deploy
      #   uses: rreichel3/vuepress-github-actions-deploy@master
      #   env:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     BUILD_DIR: docs/.vuepress/dist
      #     BUILD_SCRIPT: npm install && npm run docs:build
      #     # PAGES_CNAME: docs.s1seven.io

      - name: Update S1SevenDocVersion_PATH
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo S1SevenDocVersion_PATH=/version/$(echo $GITHUB_REF | cut -d / -f 3 | cut -d v -f 2- | cut -d . -f 1,2)/ >> $GITHUB_ENV

      - name: Install and Build
        run: |
          npm ci
          npm run doc:build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
          TARGET_FOLDER: ${{ env.S1SevenDocVersion_PATH }}
          CLEAN: true
          CLEAN_EXCLUDE: '["version"]'
